### ISSUE TITLE
encrypting breaks SIM detection

### ISSUE THREAD

**Issue by bigerl** [AOKP/device_samsung_serranoltexx#1]
When encrypting my S4 Mini LTE the device doesn't detect the SIM card anymore. So there is neither phone calls nor SMSes. This issue didn't exist in cyanogenmod 12 and was existing in cyanogenmod 13 at least for some time. 
This issue was also discussed in the cyanogenmod forum `https://web.archive.org/web/20161225153524/https://forum.cyanogenmod.org/topic/122240-no-sim-when-encrypted-encryption-on-cm13/`.

I can confirm the initial post by Bommelu from the cyanogenmod forum. 
> First my Setup:
>
>   S4 Mini Int., GT-I9515, serranoltexx
>    CM: cm-13.0-20160221-NIGHTLY-serranoltexx
>    Recovery: TWRP 3.0.0-0 from there (xda-developers, Thread with query param: t=2678420 [i'm not allowed to post Links so far])
>    Base-Band: I9195XXUBML4
>    SIM-Cards: Drillisch (DE-O2-Network), Telekom (DE-D1), some czech carrier
>    I'm in Germany (DE).
> 
> What I did (everything was done with the USB power cable connected).
>
>    Phone works fine with all SIM-Cards listed above.
>    Set Display PIN.
>    Select Encrypt, follow the wizzard, then wait until encryption is done and PIN requested.
>    Enter PIN, boots up, no SIM-sign is shown in status bar.
>    enabling/disabling flight mode fades out flight mode in restart menu (long-press).
>    shutdown. start again.
>    SIM is recognized. Popup prompts: about ~ "SIM wurde erfolgreich eingerichtet. Bitte neustarten" (SIM was successfully set up. Please Restart) with a single button "restart now". Alternatively I could click somewhere outside the popup to not restart. I clicked restart.
> The phone restarts and the SIM is not recognized again and the phone shows the no sim sign again in the status bar. Sending- and receiving SMS is possible, but making calls is not (shows not network connected). In Settings I cant open the mobile carrier/network menue (the one below WLAN and Bluetooth). Tested with all SIM-Cards listed above.

Same here with AOKP running the nightly from 2017-01-30

I assume this is an serrano-common bug but I can't confirm that so I posted it to serranoltexx.
THX a lot for anything, you're great unicorns. ;)

**Comment by csendre** [comment]
Please post a full log on boot in the official AOKP thread on XDA

**Comment by bigerl** [comment]
OK, thx. I'll do that. But it may take some time for it.

**Comment by csendre** [comment]
https://review.lineageos.org/#/c/160209/
No more need for log, this commit will fix the issue and will be merged soon

**Comment by bigerl** [comment]
Nice. I'll check the logs when it reaches the AOKP rom and try encrypting again. If it unexpectedly still won't work I'll report to the AOKP thread on XDA.
